/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_cpp_NativeCommunications */

#ifndef _Included_org_cocos2dx_cpp_NativeCommunications
#define _Included_org_cocos2dx_cpp_NativeCommunications
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_cpp_NativeCommunications
 * Method:    setBottomAdHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_NativeCommunications_setBottomAdHeight
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
